version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - library_service_backend_postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: 'redis:latest'
    container_name: "redis"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - library_service_backend_redis_data:/var/lib/redis/data
    restart: always


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - library_service_backend_rabbitmq_data_library_service:/var/lib/rabbitmq/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - library_service_backend_minio_data:/data
    restart: always


volumes:
  library_service_backend_postgres_data:
  library_service_backend_rabbitmq_data_library_service:
  library_service_backend_minio_data:
  library_service_backend_redis_data:
