spring:
  application:
    name: "Library_service_backend"

  mvc:
    hidden method:
      filter:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5434/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

  minio:
    url: http://localhost:9000
    access-key: ${MINIO_USER}
    secret-key: ${MINIO_PASSWORD}
    bucket: library_service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

token:
  signing:
    key: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - loggers

  endpoint:
    health:
      show-details: always

library:
  password-reset:
    token-ttl-minutes: 15
  daily-fine: 100
  scheduler:
    overdue-cron: "0 0 1 * * *"

app:
  frontend:
    base-url: http://localhost:8080
